### PR TITLE
Added wildcard API key information

### LINKED ISSUE #71: Document how to permit a wildcard IP on device-server
According to [this thread on together](https://together.bunq.com/d/4660-api-how-to-permit-all-ip-addresses-when-posting-a-device-server) you can add a wildcard IP to a device-server by using a `*`.

> (...) it is possible to create a wildcard key if you populate the permitted_ips with the current IP you're making calls from and * to also add wildcard.

This information is critical when you're dealing with dynamic IPs (which is most of the time I think). Therefore I think this information should be added to the documentation.

### PR DESCRIPTION
**Pull request by wvteijlingen**
See https://github.com/bunq/doc/issues/71. I think it would also be a good idea to add this to the documentation for the actual POST device-server call.

(PS: The URL in this paragraph is also out of date, but I've left it in because that's a different issue.)

Closes #71

### CODE REVIEW

**Comment by OGKevin** [comment]
@wvteijlingen for the sake of clarity, have you tried this and confirmed it working ? As by my knowledge, if you do this with the `/ip` endpoint you will get an exception. I just want to be sure if this has been confirmed in practice.

**Comment by wvteijlingen** [comment]
I'm using the `permitted_ips` field when POSTing a device-server. This does not result in an error response. I did not check if the whitelisting itself actually works. I assume it does since a Bunq employee pointed out this feature.

**Comment by OGKevin** [comment]
@JordyHeemskerk of @kojoru please conform that `/ip` still throws exception. Unless I’m missing something 😅

**Comment by Crecket** [comment]
Apparently this has always been possible so I think this can be merged

**Comment by OGKevin** [comment]
@wvteijlingen FYI 🙃

**Comment by wvteijlingen** [comment]
👍

**Pull request merged**
